# Change these first
owner: AlonsoK28 # Your GitHub organization or username, where this repository lives
repo: xadani-upptime # The name of this repository

sites:
  - name: xadani
    url: https://www.xadani.com.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556506394/assets/favicon/xadani/xadani.png
    
  - name: sterilite
    url: https://sterilite.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1543876497/assets/favicon/sterilite/sterilite
    
  - name: cajas-de-plastico
    url: https://cajas-de-plastico.com
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1542061177/assets/favicon/cajas-de-plastico/favicon.ico
    
  - name: barreras-vehiculares
    url: https://barreras-vehiculares.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1542061177/assets/favicon/cajas-de-plastico/favicon.ico
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /xadani-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
