# Change these first
owner: AlonsoK28 # Your GitHub organization or username, where this repository lives
repo: xadani-upptime # The name of this repository

sites:
  - name: xadani
    url: https://www.xadani.com.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
   
  - name: xadani-api
    url: https://www.xadani.com.mx/api/producto/cajas%20de%20plastico
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico

  - name: xadani-email
    url: https://www.xadani.com.mx/modulos/controller/contacto.php?funcion=sendTestingEmail
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    method: POST
    headers:
    - "x-secret: $XADANI_API_SECRET-$XADANI_DOMAIN_SECRET"
    - "x-token: $XADANI_API_TOKEN-$XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: xadani-stripe-create-chekout
    url: https://www.xadani.com.mx/create-checkout-stripe
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    headers:
    - "x-heart-beat: $XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"
    
  - name: xadani-stripe-order-details
    url: https://www.xadani.com.mx/order-details/0987654321
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    headers:
    - "x-heart-beat: $XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: xadani-stripe-webhook
    url: https://www.xadani.com.mx/webhook-stripe
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    headers:
    - "x-heart-beat: $XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: xadani-admin-api-batch
    url: https://www.xadani.com.mx/modulos/controller/api/v2/batch.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    headers:
    - "x-heart-beat: $XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: xadani-admin-api-keywords
    url: https://www.xadani.com.mx/modulos/controller/api/v2/keywords.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    headers:
    - "x-heart-beat: $XADANI_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: xadani-product-1
    url: https://www.xadani.com.mx/griddler-de-color-plata/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Griddler de color plata</title>"
  
  - name: xadani-product-2
    url: https://www.xadani.com.mx/dispensador-de-doble-camara/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Dispensador de doble cámara</title>"

  - name: xadani-service-1-title
    url: https://www.xadani.com.mx/servicio-de-instalacion-de-barreras-vehiculares/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Servicio de instalacion de barreras vehiculares</title>"
  
  - name: xadani-service-1-description
    url: https://www.xadani.com.mx/servicio-de-instalacion-de-barreras-vehiculares/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: '<meta name="description" content="Soluciones empresariales para el Servicio de instalacion de barreras vehiculares orientados a espacios como Oficinas, Centros comerciales y Hospitales">'
    
  - name: xadani-service-2-title
    url: https://www.xadani.com.mx/instalacion-plafon-corrido/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Instalación de Plafón Corrido | Plafones de Tablaroca Profesionales</title>"
  
  - name: xadani-service-2-description
    url: https://www.xadani.com.mx/instalacion-plafon-corrido/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: '<meta name="description" content="Servicio profesional de instalación de plafón corrido en interiores. Plafones de tablaroca modernos, funcionales y con acabados de alta calidad.">'

  - name: xadani-ecommerce
    url: https://www.xadani.com.mx/mi-ecommerce.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Crea tu tienda online: La mejor plataforma de eCommerce</title>"
  
  - name: xadani-list-1
    url: https://www.xadani.com.mx/mejores-marcas-de-herramientas/l
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>⚡  Mejores marcas de herramientas</title>"
  
  - name: xadani-cotizacion
    url: https://www.xadani.com.mx/cotizacion.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Xadani | Pídenos una cotización</title>"
  
  - name: xadani-contacto
    url: https://www.xadani.com.mx/contacto.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Xadani | Haznos llegar tu opinión</title>"
  
  - name: xadani-categoria
    url: https://www.xadani.com.mx/categoria/hogar/pagina1.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Xadani | Categoría de Hogar</title>"
  
  - name: xadani-subcategoria
    url: https://www.xadani.com.mx/subcategoria/almacenamiento/pagina1.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Xadani | Subcategoría de Almacenamiento</title>"
  
  - name: xadani-busqueda
    url: https://www.xadani.com.mx/buscar/cajas/pagina1.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Xadani | Resultados para su búsqueda de cajas</title>"
  
  - name: xadani-marca
    url: https://www.xadani.com.mx/marca/sterilite/pagina1.html
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702581615/assets/favicon/xadani/xadani-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Sterilite en Xadani</title>"
    
  - name: sterilite
    url: https://sterilite.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico

  - name: sterilite-api
    url: https://sterilite.mx/api/producto/cajas%20de%20plastico
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico

  - name: sterilite-stripe-create-chekout
    url: https://sterilite.mx/create-checkout-stripe
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"
  
  - name: sterilite-stripe-create-payment-intent
    url: https://sterilite.mx/create-payment-intent
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"
  
  - name: sterilite-stripe-checkout-form
    url: https://sterilite.mx/checkout
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Complete su compra | Sterilite Checkout</title>"
    
  - name: sterilite-stripe-order-details
    url: https://sterilite.mx/order-details/0987654321
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"
    
  - name: sterilite-stripe-webhook
    url: https://sterilite.mx/webhook-stripe
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"
    
  - name: sterilite-admin-api-batch
    url: https://sterilite.mx/modulos/controller/api/v2/batch.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: sterilite-admin-api-keywords
    url: https://sterilite.mx/modulos/controller/api/v2/keywords.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    headers:
    - "x-heart-beat: $STERILITE_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: sterilite-product-1
    url: https://sterilite.mx/mini-contenedor-de-almacenamiento-sterilite/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Mini contenedor de almacenamiento Sterilite</title>"

  - name: sterilite-product-2
    url: https://sterilite.mx/caja-con-tapa-de-bisagras-de-uso-rudo-45-litros/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Caja con tapa de bisagras de uso rudo 45 litros</title>"
  
  - name: sterilite-list-1-title
    url: https://sterilite.mx/paga-tus-productos-en-linea/l
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>🛍️ Compra Productos Sterilite en Línea - Pago Seguro</title>"
  
  - name: sterilite-list-1-description
    url: https://sterilite.mx/paga-tus-productos-en-linea/l
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702583888/assets/favicon/sterilite/sterilite-2.0.ico
    __dangerous__body_down_if_text_missing: '<meta name="description" content="Ahora puedes pagar en línea tus productos Sterilite favoritos. Compra fácil, rápido y seguro. ¡Organiza tu hogar sin complicaciones! 🚀">'
    
    
  - name: cajas-de-plastico
    url: https://cajas-de-plastico.com
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico

  - name: cajas-de-plastico-api
    url: https://cajas-de-plastico.com/api/producto/cajas%20de%20plastico
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico

  - name: cajas-de-plastico-admin-api-batch
    url: https://cajas-de-plastico.com/modulos/controller/api/v2/batch.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico
    headers:
    - "x-heart-beat: $CAJAS_DE_PLASTICO_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: cajas-de-plastico-admin-api-keywords
    url: https://cajas-de-plastico.com/modulos/controller/api/v2/keywords.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico
    headers:
    - "x-heart-beat: $CAJAS_DE_PLASTICO_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: cajas-de-plastico-product-1
    url: https://cajas-de-plastico.com/contenedor-de-almacenamiento-apilable-rubbermaid/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Contenedor de almacenamiento apilable Rubbermaid</title>"
  
  - name: cajas-de-plastico-product-2
    url: https://cajas-de-plastico.com/cajas-de-almacenamiento-con-cerradura-de-24-galones-rubbermaid/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>Cajas de almacenamiento con cerradura de 24 galones Rubbermaid</title>"
  
  - name: cajas-de-plastico-list-1
    url: https://cajas-de-plastico.com/catalogo-de-cajas-de-almacenamiento-de-la-marca-rubbermaid/l
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1702584172/assets/favicon/cajas-de-plastico/favicon-2.0.ico
    __dangerous__body_down_if_text_missing: "<title>⚡ Cajas de Plástico | catalogo de cajas de almacenamiento de la marca rubbermaid</title>"
    
  - name: barreras-vehiculares
    url: https://barreras-vehiculares.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png

  - name: barreras-vehiculares-api
    url: https://barreras-vehiculares.mx/api/producto/barreras
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png

  - name: barreras-vehiculares-admin-api-batch
    url: https://barreras-vehiculares.mx/modulos/controller/api/v2/batch.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    headers:
    - "x-heart-beat: $BARRERAS_VEHICULARES_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: barreras-vehiculares-admin-api-keywords
    url: https://barreras-vehiculares.mx/modulos/controller/api/v2/keywords.php
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    headers:
    - "x-heart-beat: $BARRERAS_VEHICULARES_DOMAIN_SECRET"
    - "Content-Type: application/json"

  - name: barreras-vehiculares-product-1
    url: https://barreras-vehiculares.mx/barrera-vehicular-automatica-gard8-para-mastil-de-hasta-7-metros-came/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: "<title>Barrera Vehicular automática GARD8 para mástil de hasta 7.6 metros  CAME</title>"
  
  - name: barreras-vehiculares-product-2
    url: https://barreras-vehiculares.mx/barrera-vehicular-came-alto-rendimiento-con-brazo-de-hasta-4-mts/p
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: "<title>Barrera Vehicular  CAME Alto Rendimiento con Brazo de Hasta 4 Mts</title>"
  
  - name: barreras-vehiculares-service-1-title
    url: https://barreras-vehiculares.mx/instalacion-de-barreras-vehiculares/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: "<title>Instalacion de barreras vehiculares</title>"
  
  - name: barreras-vehiculares-service-1-description
    url: https://barreras-vehiculares.mx/instalacion-de-barreras-vehiculares/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: '<meta name="description" content="Instalacion de barreras vehiculares">'
  
  - name: barreras-vehiculares-service-2-title
    url: https://barreras-vehiculares.mx/servicio-de-instalacion-de-barreras-vehiculares-en-zonas-residenciales/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: "<title>Servicio de instalacion de barreras vehiculares en zonas residenciales</title>"
  
  - name: barreras-vehiculares-service-2-description
    url: https://barreras-vehiculares.mx/servicio-de-instalacion-de-barreras-vehiculares-en-zonas-residenciales/s
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1556505787/assets/favicon/barreras-vehiculares/icono-control-de-acceso-vehicular.png
    __dangerous__body_down_if_text_missing: '<meta name="description" content="Servicio de instalacion de barreras vehiculares en zonas residenciales">'

  - name: verificador-precios
    url: https://verificador-precios.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1734548123/assets/favicon/xadani/xadani-3.0.ico
  
  - name: verificador-precios software
    url: https://verificador-precios.mx/software/
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1734548123/assets/favicon/xadani/xadani-3.0.ico

  - name: verificador-precios pospal
    url: https://verificador-precios.mx/verificador-precios-integracion-pospal/
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1734548123/assets/favicon/xadani/xadani-3.0.ico

  - name: consultoria-angular
    url: https://consultoria-angular.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1734548123/assets/favicon/xadani/xadani-3.0.ico

  - name: punto-facturacion
    url: https://punto-facturacion.mx
    icon: https://res.cloudinary.com/xadani-mexico/image/upload/v1734548123/assets/favicon/xadani/xadani-3.0.ico
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /xadani-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10999 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
